//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RX_SCREENINGEntities : DbContext
    {
        public RX_SCREENINGEntities()
            : base("name=RX_SCREENINGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AssignRider> AssignRider { get; set; }
        public DbSet<MedicalStore> MedicalStore { get; set; }
        public DbSet<Medicine> Medicine { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<OrderMedicine> OrderMedicine { get; set; }
        public DbSet<Place> Place { get; set; }
        public DbSet<Prescription> Prescription { get; set; }
        public DbSet<Profile> Profile { get; set; }
        public DbSet<Rider> Rider { get; set; }
        public DbSet<StoreMedicine> StoreMedicine { get; set; }
        public DbSet<User> User { get; set; }
    }
}
