//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public Medicine()
        {
            this.OrderMedicine = new HashSet<OrderMedicine>();
            this.StoreMedicine = new HashSet<StoreMedicine>();
        }
    
        public int MedicineId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ICollection<OrderMedicine> OrderMedicine { get; set; }
        public virtual ICollection<StoreMedicine> StoreMedicine { get; set; }
    }
}
