//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderMedicine = new HashSet<OrderMedicine>();
            this.Place = new HashSet<Place>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RiderId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> Bill { get; set; }
        public string Status { get; set; }
    
        public virtual Rider Rider { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<OrderMedicine> OrderMedicine { get; set; }
        public virtual ICollection<Place> Place { get; set; }
    }
}
