//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int ProfileId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string PName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string Allergy { get; set; }
        public string MedicalHistory { get; set; }
    
        public virtual User User { get; set; }
    }
}
