//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreMedicine
    {
        public int StoreMedicineId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> MedicineId { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public Nullable<System.DateTime> ManufacturingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
    
        public virtual MedicalStore MedicalStore { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
