//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fyp_rx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Order = new HashSet<Order>();
            this.Prescription = new HashSet<Prescription>();
            this.Profile = new HashSet<Profile>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Prescription> Prescription { get; set; }
        public virtual ICollection<Profile> Profile { get; set; }
    }
}
